<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\models\yolov8n.onnx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\models\yolov8n.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
    <PackageReference Include="YoloDotNet" Version="4.2.0" />
    <PackageReference Include="YoloDotNet.ExecutionProvider.Cpu" Version="1.1.0" />
  </ItemGroup>

</Project>
